name: route-codegen CI
on:
  push:
    branches-ignore:
      - "master"
jobs:
  test:
    name: Run tests on NodeJS
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build:core

      - name: Run tests
        run: yarn test:core

      - name: Check that samples are generated
        run: ./scripts/ci/check-sample.sh
