name: "@route-codegen/utils prerelease"
on:
  push:
    branches:
      - "master"
    paths:
      - "packages/utils/**"
jobs:
  release-alpha:
    runs-on: ubuntu-18.04
    name: Release @route-codegen/utils alpha

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build:utils

      - name: Run tests
        run: yarn test:utils

      - name: Publish alpha
        # https://github.com/actions/setup-node/issues/81
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          ./scripts/ci/prerelease.sh @route-codegen/utils packages/utils
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
