name: "@route-codegen/react prerelease"
on:
  pull_request:
    branches:
      - master
    paths:
      - "packages/react/**"
jobs:
  release-alpha:
    runs-on: ubuntu-18.04
    name: Release @route-codegen/react alpha

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build:react

      - name: Publish alpha
        # https://github.com/actions/setup-node/issues/81
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          ./scripts/ci/prerelease.sh @route-codegen/react packages/react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
