name: "Prerelease utils"
on:
  pull_request:
    branches:
      - "master"
    paths:
      - "packages/utils/**"
jobs:
  release-alpha:
    runs-on: ubuntu-18.04
    name: Release @route-codegen/utils alpha

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build:utils

      - name: Run tests
        run: yarn test:utils

      - name: Set up NPM credentials
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish alpha
        run: ./scripts/ci/prerelease.sh @route-codegen/utils packages/utils
