name: "Prerelease core"
on:
  pull_request:
    branches:
      - "master"
    paths:
      - "packages/core/**"
jobs:
  release-alpha:
    runs-on: ubuntu-18.04
    name: Release @route-codegen/core alpha

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build:core

      - name: Run tests
        run: yarn test:core

      - name: Set up NPM credentials
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish alpha
        run: ./scripts/ci/prerelease.sh @route-codegen/core packages/core
