name: route-codegen release alpha
# on:
#   pull_request:
#     types: [closed]
on: [push, pull_request]
jobs:
  test-on-merge:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    name: Test on merge

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test

  release-alpha:
    # if: github.event.pull_request.merged == true
    needs: test-on-merge
    runs-on: ubuntu-18.04
    name: Release alpha

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build
