name: route-codegen release alpha
on:
  push:
    branches:
      - 'master'
    paths:
      - 'src/**'
jobs:
  test-on-merge:
    runs-on: ubuntu-18.04
    name: Test on merge

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Publish alpha
        # https://github.com/actions/setup-node/issues/81
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          ./bin/prerelease.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
