name: route-codegen release alpha
on:
  release:
    types: [published]
jobs:
  #   test-on-publish:
  #     runs-on: ubuntu-18.04
  #     name: Test on publish

  #     strategy:
  #       matrix:
  #         node-version: [10.x, 12.x]

  #     steps:
  #       - name: Check out repository
  #         uses: actions/checkout@v2

  #       - name: Set up Node.js ${{ matrix.node-version }}
  #         uses: actions/setup-node@v1
  #         with:
  #           node-version: ${{ matrix.node-version }}

  #       - name: Install packages
  #         run: yarn --frozen-lockfile

  #       - name: Build
  #         run: yarn build

  #       - name: Run tests
  #         run: yarn test

  release:
    # needs: test-on-publish
    runs-on: ubuntu-18.04
    name: Release

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Setup GIT
        run: |
          git switch -c master
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

      - name: Publish new version
        # https://github.com/actions/setup-node/issues/81
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          ./bin/release.sh ${{ github.event.release.tag_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Update master
        run: git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
